import { Component } from '@angular/core';
import { HeaderComponent } from '../app/header.component/header.component';
import { MainLabelComponent } from '../app/main-label/main-label';
import { CommonModule } from '@angular/common';
import { KanbanCard } from '../app/kanban-card/kanban-card';

@Component({
  selector: 'app-mc-board',
  imports: [HeaderComponent, MainLabelComponent, CommonModule, KanbanCard],
  templateUrl: './mc-board.html',
  styleUrl: './mc-board.css',
})
export class McBoard {
  trackByTitle(index: number, task: any) {
    return task.title;
  }


  columns = [
    {
      title: 'To Do',
      color: '#E9A015',
      tasks: [
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
      ],
    },
    {
      title: 'In Progress',
      color: '#9A0000',
      tasks: [
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
      ],
    },
    {
      title: 'Review',
      color: '#5F0707',
      tasks: [
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
      ],
    },
    {
      title: 'Mechanical',
      color: '#BC9595',
      tasks: [],
    },
    {
      title: 'Completed',
      color: '#26B524',
      tasks: [
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
        {
          title: 'Screen Acting Skills',
          tasksRemaining: 4,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 3,
          collection: 'Email',
          year: 2021,
          avatars: ['CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Subject Headings', user: 'Derven' },
            { type: 'Quality Check', user: 'Matthew' },
          ],
        },
        {
          title: 'Screen Voting Skills',
          tasksRemaining: 2,
          collection: 'SMS',
          year: 2020,
          avatars: ['AA', 'BB', 'CC'],
          subtasks: [
            { type: 'Metadata Entry', user: 'Gian' },
            { type: 'Classification', user: 'Balong' },
          ],
        },
        {
          title: 'Media Experiences: Engaging W...',
          tasksRemaining: 1,
          collection: 'Email',
          year: 2021,
          avatars: ['CC', 'DD'],
          subtasks: [{ type: 'Quality Check', user: 'Matthew' }],
        },
      ],
    },
  ];
}
